<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Hello' => '',
    'If you cannot click the link, please try pasting the text into your browser.' => '',
    'If you did not make this request you can ignore this email.' => '',
    'In order to complete your registration, please click the link below.' => '',
    'In order to complete your request, please click the link below.' => '',
    'Please click the link below to complete your password reset.' => '',
    'Thank you for signing up on {0}.' => '',
    'We have generated a password for you' => '',
    'We have generated a password for you:' => '',
    'We have generated a password for you: ' => '',
    'We have received a request to change the email address for your account on {0}.' => '',
    'We have received a request to reset the password for your account on {0}.' => '',
    'Your account on {0} has a new password.' => '',
    'Your account on {0} has been created.' => '',
];
